// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: contract/sms/send.proto

package sms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MessageId      int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SourceNumber   string                 `protobuf:"bytes,3,opt,name=source_number,json=sourceNumber,proto3" json:"source_number,omitempty"`
	ReceptorNumber string                 `protobuf:"bytes,4,opt,name=receptor_number,json=receptorNumber,proto3" json:"receptor_number,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SmsRequest) Reset() {
	*x = SmsRequest{}
	mi := &file_contract_sms_send_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsRequest) ProtoMessage() {}

func (x *SmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_sms_send_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsRequest.ProtoReflect.Descriptor instead.
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return file_contract_sms_send_proto_rawDescGZIP(), []int{0}
}

func (x *SmsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SmsRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SmsRequest) GetSourceNumber() string {
	if x != nil {
		return x.SourceNumber
	}
	return ""
}

func (x *SmsRequest) GetReceptorNumber() string {
	if x != nil {
		return x.ReceptorNumber
	}
	return ""
}

func (x *SmsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SmsRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

var File_contract_sms_send_proto protoreflect.FileDescriptor

const file_contract_sms_send_proto_rawDesc = "" +
	"\n" +
	"\x17contract/sms/send.proto\x12\bpresence\"\xd6\x01\n" +
	"\n" +
	"SmsRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12#\n" +
	"\rsource_number\x18\x03 \x01(\tR\fsourceNumber\x12'\n" +
	"\x0freceptor_number\x18\x04 \x01(\tR\x0ereceptorNumber\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattemptB Z\x1esmsgateway/contract/golang/smsb\x06proto3"

var (
	file_contract_sms_send_proto_rawDescOnce sync.Once
	file_contract_sms_send_proto_rawDescData []byte
)

func file_contract_sms_send_proto_rawDescGZIP() []byte {
	file_contract_sms_send_proto_rawDescOnce.Do(func() {
		file_contract_sms_send_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_sms_send_proto_rawDesc), len(file_contract_sms_send_proto_rawDesc)))
	})
	return file_contract_sms_send_proto_rawDescData
}

var file_contract_sms_send_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contract_sms_send_proto_goTypes = []any{
	(*SmsRequest)(nil), // 0: presence.SmsRequest
}
var file_contract_sms_send_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_sms_send_proto_init() }
func file_contract_sms_send_proto_init() {
	if File_contract_sms_send_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_sms_send_proto_rawDesc), len(file_contract_sms_send_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_sms_send_proto_goTypes,
		DependencyIndexes: file_contract_sms_send_proto_depIdxs,
		MessageInfos:      file_contract_sms_send_proto_msgTypes,
	}.Build()
	File_contract_sms_send_proto = out.File
	file_contract_sms_send_proto_goTypes = nil
	file_contract_sms_send_proto_depIdxs = nil
}
